### ISSUE TITLE
点击选择部门或成员，既没有报错也没有请求接口，请问是为什么呀？

### ISSUE THREAD

**Issue by coder-575** [liulixi/Vue-Weixin-JS-SDK#1]

**Comment by x-player-001** [comment]
config 接口和 agentconfig 接口注册成功了吗

**Comment by coder-575** [comment]
> config 接口和 agentconfig 接口注册成功了吗

我们不是第三方应用开发啊 只需要走config接口吧？

**Comment by coder-575** [comment]
> config 接口和 agentconfig 接口注册成功了吗

注册成功之后是不是还要配置可信域名啊？
